const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const root=path.join(__dirname,'..');
const app=fs.existsSync(path.join(root,'dist/app.js'))?path.join(root,'dist/app.js'):path.join(root,'app.js');
const source=fs.readFileSync(app,'utf8').replace(/\nboot\(\);/,'\n// boot disabled for logic tests');
function lab(){const c=vm.createContext({console,Intl,URL,Uint8Array,crypto:require('node:crypto').webcrypto,setTimeout:(f)=>{f();return 1},clearTimeout:()=>{},localStorage:{getItem:()=>null},document:{}});vm.runInContext(source,c);return expr=>vm.runInContext(expr,c);}
function fixture(run){run(`state=fresh(); function install(t,z,capability){ state.products[t]=[{name:'Test',supplier:'QA',description:'Test evidence description',url:'https://example.com',image:'https://example.com/image.png',priceNote:'QA fixture only',price:100,capability}];state.placements.push({id:t+'-'+z,type:t,zone:z,slot:0,reason:'Justified classroom test fixture'}); } function own(id){state.procedures[id]=true;state.procedureNotes[id]='Facilities manager checks and records this every week.';}`);}
test('all 12 baseline incidents are deterministic and have zero checks addressed',()=>{const r=lab();assert.equal(r('SCENARIOS.length'),12);assert.equal(r('SCENARIOS.every(s=>evaluate(s[0]).score===0)'),true);assert.equal(r('JSON.stringify(evaluate("heat"))===JSON.stringify(evaluate("heat"))'),true);});
test('UPS capability is required; surge protectors and unknown legacy products fail outage protection',()=>{const r=lab();fixture(r);r('install("power","server","surge")');assert.equal(r('evaluate("power").checks[0].ok'),false);r('state.products.power[0].capability="ups"');assert.equal(r('evaluate("power").checks[0].ok'),true);r('delete state.products.power[0].capability');assert.equal(r('evaluate("power").checks[0].ok'),false);});
test('asset marking cannot stop laptop removal',()=>{const r=lab();fixture(r);r('install("devicelock","office","marking")');assert.equal(r('evaluate("laptop").checks[0].ok'),false);r('state.products.devicelock[0].capability="anchor"');assert.equal(r('evaluate("laptop").checks[0].ok'),true);});
test('fencing alone is not vehicle resistance',()=>{const r=lab();fixture(r);r('install("barriers","perimeter","fence")');assert.equal(r('evaluate("vehicle").checks[0].ok'),false);r('state.products.barriers[0].capability="vehicle"');assert.equal(r('evaluate("vehicle").checks[0].ok'),true);});
test('failed primary cooling earns no points; standby plus an owned plan addresses failure',()=>{const r=lab();fixture(r);r('install("cooling","server")');assert.equal(r('evaluate("heat").score'),0);r('install("backupcool","server");own("coolplan")');assert.equal(r('evaluate("heat").score'),100);});
test('evacuation can operate without buying suppression; unnamed procedures receive no credit',()=>{const r=lab();fixture(r);r('state.procedures.fireplan=true');assert.equal(r('evaluate("fire").checks[1].ok'),false);r('own("fireplan")');assert.equal(r('evaluate("fire").checks[1].ok'),true);});
test('biometric server access receives credit and wrong-zone CCTV does not',()=>{const r=lab();fixture(r);r('install("biometric","server");install("cctv","reception");own("response")');assert.equal(r('evaluate("server").checks[0].ok'),true);assert.equal(r('evaluate("server").checks[3].ok'),false);});
test('records response requires local detection, and CCTV is an alternative to motion',()=>{const r=lab();fixture(r);r('install("cctv","office");own("response")');assert.equal(r('evaluate("records").checks[3].ok'),false);r('install("cctv","records")');assert.equal(r('evaluate("records").checks[1].ok && evaluate("records").checks[3].ok'),true);});
test('fingerprint tracks effectiveness, not notes, supplier prices or duplicate runs',()=>{const r=lab();fixture(r);r('install("power","server","surge"); const before=signature(); state.products.power[0].price=200;state.predictions.power="Prediction"');assert.equal(r('signature()===before'),true);r('state.products.power[0].capability="ups"');assert.equal(r('signature()===before'),false);r('state.runs=[{id:"power",signature:signature(),score:33},{id:"power",signature:signature(),score:33}]');assert.equal(r('staleRuns()'),false);assert.equal(r('latestRuns().length'),1);});
test('snapshot evaluation ignores subsequent live design mutations',()=>{const r=lab();fixture(r);r('install("power","server","ups");const snapshot=JSON.parse(JSON.stringify(state));state.placements=[]');assert.equal(r('evaluate("power",snapshot).checks[0].ok'),true);assert.equal(r('evaluate("power").checks[0].ok'),false);});
test('v2 saves retain research, placement and answers; v3 preserves learning journal',()=>{const r=lab();fixture(r);r('install("power","server");state.answers.q1={text:"A control explanation",mark:1};state.version=2;state=validateState(JSON.parse(JSON.stringify(state)))');assert.equal(r('state.placements.length'),1);assert.equal(r('state.version'),3);r('state.predictions.power="I predict a gap";state.debriefs.power="Buy battery backup";state=validateState(JSON.parse(JSON.stringify(state)))');assert.equal(r('state.debriefs.power'),'Buy battery backup');assert.equal(r('state.answers.q1.mark'),1);});
test('all rooms reachable from outside and each internal room has a corridor doorway',()=>{const r=lab();assert.equal(r(`(()=>{const seen=new Set(['outside']);let changed=true;while(changed){changed=false;for(const [a,b] of CONNECTIONS){if(seen.has(a)&&!seen.has(b)){seen.add(b);changed=true}if(seen.has(b)&&!seen.has(a)){seen.add(a);changed=true}}}return ZONES.every(z=>seen.has(z[0]))})()`),true);assert.equal(r(`ZONES.filter(z=>z[0]!=='perimeter').every(z=>DOORS.some(d=>d[0]===z[0]&&(d[2]===350||d[2]===430)&&d[1]>z[2]&&d[1]<z[2]+z[4]))`),true);});
test('all views render with a fresh mission and imported evidence is escaped in debrief',()=>{const r=lab();for(const view of ['homeView','planView','researchView','simView','examView','reportView','briefView'])assert.ok(r(`${view}().length`)>100);assert.equal(r(`resultView({id:'power',checks:[{ok:false,text:'<img src=x onerror=alert(1)>'}],score:0,signature:'old'}).includes('&lt;img')`),true);});
